# Generated by Django 4.1.7 on 2023-03-01 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departmentname', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regno', models.IntegerField()),
                ('dob', models.DateField()),
                ('image', models.ImageField(upload_to='')),
                ('Fname', models.CharField(max_length=100)),
                ('Lname', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('phone', models.BigIntegerField()),
                ('email', models.CharField(max_length=100)),
                ('specilization', models.CharField(max_length=100)),
                ('d_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ehr_app.departments')),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospitalname', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('place', models.CharField(max_length=100)),
                ('pincode', models.BigIntegerField()),
                ('phone', models.BigIntegerField()),
                ('email', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('usertype', models.CharField(default='pending', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(max_length=100)),
                ('Lname', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('dob', models.DateField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('l_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ehr_app.login')),
            ],
        ),
        migrations.CreateModel(
            name='userrecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('records', models.FileField(upload_to='')),
                ('date', models.DateField()),
                ('d_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ehr_app.doctor')),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ehr_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strength', models.IntegerField()),
                ('available', models.IntegerField()),
                ('Fromtime', models.TimeField()),
                ('Totime', models.TimeField()),
                ('d_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ehr_app.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=100)),
                ('AN', models.CharField(max_length=100)),
                ('FN', models.CharField(max_length=100)),
                ('Fromtime', models.TimeField()),
                ('Totime', models.TimeField()),
                ('H_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ehr_app.hospital')),
                ('d_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ehr_app.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('d_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ehr_app.doctor')),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ehr_app.user')),
            ],
        ),
        migrations.AddField(
            model_name='hospital',
            name='l_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ehr_app.login'),
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('H_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ehr_app.hospital')),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ehr_app.user')),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='l_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ehr_app.login'),
        ),
        migrations.AddField(
            model_name='departments',
            name='H_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ehr_app.hospital'),
        ),
      
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bdate', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('d_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ehr_app.doctor')),
                ('s_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ehr_app.schedule')),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ehr_app.user')),
            ],
        ),
    ]
