# Generated by Django 4.1.7 on 2023-03-02 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ehr_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='Lname',
            new_name='place',
        ),
    ]
