# Generated by Django 4.1.7 on 2023-03-02 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr_app', '0002_rename_lname_doctor_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='lattitude',
            field=models.FloatField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='logitude',
            field=models.FloatField(default=5),
            preserve_default=False,
        ),
    ]
