# Generated by Django 4.1.7 on 2023-03-02 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ehr_app', '0004_hospital_lattitude_hospital_logitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='AN',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='FN',
        ),
    ]
