# Generated by Django 4.1.7 on 2023-03-02 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr_app', '0005_remove_schedule_an_remove_schedule_fn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='Fromtime',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='Totime',
            field=models.CharField(max_length=20),
        ),
    ]
