# Generated by Django 4.1.7 on 2023-03-08 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr_app', '0008_alter_doctor_regno_alter_hospital_hospitalname'),
    ]

    operations = [
        migrations.AddField(
            model_name='departments',
            name='description',
            field=models.CharField(default=6, max_length=100),
            preserve_default=False,
        ),
    ]
