# Generated by Django 4.1.7 on 2023-03-08 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr_app', '0009_departments_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departments',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
