# Generated by Django 4.1.7 on 2023-03-09 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr_app', '0010_alter_departments_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='description',
            field=models.CharField(default=8, max_length=500),
            preserve_default=False,
        ),
    ]
