# Generated by Django 4.1.7 on 2023-03-11 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr_app', '0012_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default=9, upload_to=''),
            preserve_default=False,
        ),
    ]
