# Generated by Django 4.1.7 on 2023-03-12 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr_app', '0013_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='Fromtime',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='Totime',
            field=models.CharField(max_length=30),
        ),
    ]
