# Generated by Django 4.1.7 on 2023-03-12 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr_app', '0014_alter_schedule_fromtime_alter_schedule_totime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='d_id',
        ),
        migrations.AddField(
            model_name='booking',
            name='sloat',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
