# Generated by Django 4.1.7 on 2023-03-25 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr_app', '0017_remove_userrecord_u_id_userrecord_b_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrecord',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
