# Generated by Django 4.1.7 on 2023-04-11 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ehr_app', '0019_remove_feedback_h_id_feedback_email_feedback_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='email',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='subject',
        ),
    ]
